---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vaccination-center-service
  name: vaccination-center-service
spec:
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: vaccination-center-service
  type: ClusterIP
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccination-center-service
  labels:
    app: vaccination-center-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaccination-center-service
  template:
    metadata:
      labels:
        app: vaccination-center-service
    spec:
      containers:
      - name: vaccination-center-service
        image: naveen0005/capstone1:vaccination-center-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
        - name: servername_eureka
          value: "eureka-server"
        - name: servername_mongodb
          value: "mongodb"
...
